### ISSUE TITLE
Fatal Error - Plugin Conflict

### ISSUE THREAD

**Issue by mrjcgoodwin** [gedex/wp-slack#22]
I'm trying to activate this plugin on a site that uses the Event Organiser plugin.

Fatal error: Call to undefined function get_current_screen() .... /wp-content/plugins/event-organiser-fes/admin/manage.php on line 27

However this thread (https://github.com/stephenharris/Event-Organiser/issues/34) regarding a similar conflict between EO and another plugin would suggest the problem does not lay with them.

**Comment by gedex** [comment]
@mrjcgoodwin That's weird that plugin activation would causing that. A simple fix from EO plugin would be to check if `get_current_screen` func exists or not. Please reopen if the issue persists with stack trace.
