### ISSUE TITLE
Activation of plugin not possible in 4.7.3?

### ISSUE THREAD

**Issue by uded** [gedex/wp-slack#54]
Running latest WP: 4.7.3
Plugin from WP repo, automatic install.

Installation went without any issues, but activation is blocked somehow. WP is telling me that it was successful, but the plugin is not active at all. Any log? Any suggestions?

**Comment by gedex** [comment]
@uded Sorry for delayed response. I've tested this with 4.7.3 and just released 0.6.0 today. Can you try again?

**Comment by uded** [comment]
Hi, sorry - moved away from this plugin. Closing for now as no one else reported or participated.
