### ISSUE TITLE
Dead front-end on 0.6.0/4.7.3

### ISSUE THREAD

**Issue by kylesureline** [gedex/wp-slack#57]
Plugin activates and works in the backend, but front end of the site is blank.

**Comment by gedex** [comment]
@kylesureline I'm not able to reproduce this with 4.7.3. Could you try enable `WP_DEBUG` and get the error message. See https://codex.wordpress.org/Common_WordPress_Errors#The_White_Screen_of_Death.

This plugin doesn't do anything on the front-end side fwiw.
